<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findLastPosts()
    {
        return $this->getEntityManager()->createQuery('
            SELECT p FROM BlogBundle:Post
            WHERE p.createdAt < CURRENT_TIMESTAMP()
            ORDER BY p.createdAt DESC
        ')->setMaxResults(10)
            ->getResult();
    }

    public function findLastPosts2()
    {
        return $this->createQueryBuilder('p')
            ->where('p.createAt <= CURRENT_TIMESTAMP()')
            ->orderBy('p.createdAt DESC')
            ->setMaxResults(10)
            ->getQuery()
            ->getResult();
    }
}
