<?php

namespace BlogBundle\Repository;

/**
 * TestCrudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestCrudRepository extends \Doctrine\ORM\EntityRepository
{
}
